### ISSUE TITLE
Deprecation of /tokeninfo

### ISSUE THREAD

**Issue by thomaspeitz** [lukeoliff/auth0-elixir-countdown#6]
Hi,

thanks for your guide. Sadly it does not work for clients with "OIDC Conformant" enabled. Disabling this did not help (even after 30 minutes).

Route to /tokeninfo gives 404 which throws error.

Greetings, Thomas

**Comment by woloski** [comment]
Yes, this impl is not OIDC/oauth2 conformant. We have to move it to use https://github.com/ueberauth/ueberauth which is plain oauth2.
